In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [2]:
# downloading data
data = "https://raw.githubusercontent.com/gastonstat/CreditScoring/master/CreditScoring.csv"
!wget $data

--2026-05-25 23:48:19--  https://raw.githubusercontent.com/gastonstat/CreditScoring/master/CreditScoring.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 182489 (178K) [text/plain]
Saving to: ‘CreditScoring.csv.5’

CreditScoring.csv.5 100%[===================>] 178.21K  --.-KB/s    in 0.02s

2026-05-25 23:48:20 (9.48 MB/s) - ‘CreditScoring.csv.5’ saved [182489/182489]

In [3]:
df = pd.read_csv('CreditScoring.csv')

In [4]:
df.head()

,Status,Seniority,Home,Time,Age,Marital,Records,Job,Expenses,Income,Assets,Debt,Amount,Price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [5]:
#standardise column names 
df.columns = df.columns.str.lower()

In [6]:
df.dtypes

status       int64
seniority    int64
home         int64
time         int64
age          int64
marital      int64
records      int64
job          int64
expenses     int64
income       int64
assets       int64
debt         int64
amount       int64
price        int64
dtype: object

In [7]:
# decoding categorical variables from R 
df.status = df.status.map({1: 'ok', 2: 'default', 0: 'unknown'})

df.home = df.home.map({
    1: 'rent', 
    2: 'owner',
    3: 'priv',
    4: 'ignore',
    5: 'parents',
    6: 'other',
    0: 'unknown'})

df.marital = df.marital.map({
    1: 'single', 
    2: 'married',
    3: 'widow',
    4: 'separated',
    5: 'divorced',
    0: 'unknown'
})

df.records = df.records.map({
    1: 'no_rec', 
    2: 'yes_rec'})

df.job = df.job.map({
    1: 'fixed', 
    2: 'partime',
    3: 'freelance',
    4: 'others',
    0: 'unknown'})

In [8]:
df[['marital', 'home', 'status', 'records', 'job']] = df[['marital', 'home', 'status', 'records', 'job']].astype('str')

In [9]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no_rec,freelance,73,129,0,0,800,846
1,ok,17,rent,60,58,widow,no_rec,fixed,48,131,0,0,1000,1658
2,default,10,owner,36,46,married,yes_rec,freelance,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,single,no_rec,fixed,63,182,2500,0,900,1325
4,ok,0,rent,36,26,single,no_rec,fixed,46,107,0,0,310,910

In [10]:
#Get statistical summary of the numerical columns
df.describe().round()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0
mean,8.0,46.0,37.0,56.0,763317.0,1060341.0,404382.0,1039.0,1463.0
std,8.0,15.0,11.0,20.0,8703625.0,10217569.0,6344253.0,475.0,628.0
min,0.0,6.0,18.0,35.0,0.0,0.0,0.0,100.0,105.0
25%,2.0,36.0,28.0,35.0,80.0,0.0,0.0,700.0,1118.0
50%,5.0,48.0,36.0,51.0,120.0,3500.0,0.0,1000.0,1400.0
75%,12.0,60.0,45.0,72.0,166.0,6000.0,0.0,1300.0,1692.0
max,48.0,72.0,68.0,180.0,99999999.0,99999999.0,99999999.0,5000.0,11140.0

In [11]:
numericals = list(df.dtypes[df.dtypes == 'int'].index)

In [12]:
#replace columns with null values with actual numpy nan
for col in numericals:
    df[col] = df[col].replace(99999999.0, np.nan)

In [13]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no_rec,freelance,73,129.0,0.0,0.0,800,846
1,ok,17,rent,60,58,widow,no_rec,fixed,48,131.0,0.0,0.0,1000,1658
2,default,10,owner,36,46,married,yes_rec,freelance,90,200.0,3000.0,0.0,2000,2985
3,ok,0,rent,60,24,single,no_rec,fixed,63,182.0,2500.0,0.0,900,1325
4,ok,0,rent,36,26,single,no_rec,fixed,46,107.0,0.0,0.0,310,910

In [14]:
df.isnull().sum()

status        0
seniority     0
home          0
time          0
age           0
marital       0
records       0
job           0
expenses      0
income       34
assets       47
debt         18
amount        0
price         0
dtype: int64

In [15]:
# fill null values with median
df[['income', 'assets', 'debt']] = df[['income', 'assets', 'debt']].fillna(df[['income', 'assets', 'debt']].median())

In [16]:
df.describe()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.000000,4455.000000,4455.000000,4455.000000,4455.000000,4455.000000,4455.000000,4455.000000,4455.000000
mean,7.987205,46.441751,37.077666,55.568799,130.487542,5378.077890,341.562963,1039.021773,1462.875645
std,8.173444,14.655225,10.984856,19.515878,86.042072,11514.557029,1243.532086,474.543007,628.089913
min,0.000000,6.000000,18.000000,35.000000,0.000000,0.000000,0.000000,100.000000,105.000000
25%,2.000000,36.000000,28.000000,35.000000,80.000000,0.000000,0.000000,700.000000,1117.500000
50%,5.000000,48.000000,36.000000,51.000000,120.000000,3000.000000,0.000000,1000.000000,1400.000000
75%,12.000000,60.000000,45.000000,72.000000,164.000000,6000.000000,0.000000,1300.000000,1692.000000
max,48.000000,72.000000,68.000000,180.000000,959.000000,300000.000000,30000.000000,5000.000000,11140.000000

In [17]:
#convert the target variable into binary 

df['status'] = (df['status'] == 'default').astype('int')

In [18]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,0,9,rent,60,30,married,no_rec,freelance,73,129.0,0.0,0.0,800,846
1,0,17,rent,60,58,widow,no_rec,fixed,48,131.0,0.0,0.0,1000,1658
2,1,10,owner,36,46,married,yes_rec,freelance,90,200.0,3000.0,0.0,2000,2985
3,0,0,rent,60,24,single,no_rec,fixed,63,182.0,2500.0,0.0,900,1325
4,0,0,rent,36,26,single,no_rec,fixed,46,107.0,0.0,0.0,310,910

In [20]:
#Study the status column
global_default = df['status'].mean()
global_default

np.float64(0.2814814814814815)