In [171]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [172]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'
!wget $data -O data-week-3.csv

--2026-04-27 21:34:57--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 977501 (955K) [text/plain]
Saving to: ‘data-week-3.csv’

data-week-3.csv     100%[===================>] 954.59K  --.-KB/s    in 0.05s

2026-04-27 21:34:57 (19.9 MB/s) - ‘data-week-3.csv’ saved [977501/977501]

In [173]:
df = pd.read_csv('data-week-3.csv')

In [174]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [175]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

# Data Standardisation

In [176]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
strings = list(df.dtypes[df.dtypes == 'object'].index)

for col in strings:
  df[col] = df[col].str.lower().str.replace(' ', '_')

In [177]:
df.head().T

,0,1,2,3,4
customerid,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu
gender,female,male,male,male,female
seniorcitizen,0,0,0,0,0
partner,yes,no,no,no,no
dependents,no,no,no,no,no
tenure,1,34,2,45,2
phoneservice,no,yes,yes,no,yes
multiplelines,no_phone_service,no,no,no_phone_service,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic
onlinesecurity,no,yes,yes,yes,no
onlinebackup,yes,no,yes,no,no
deviceprotection,no,yes,no,yes,no
techsupport,no,no,no,yes,no
streamingtv,no,no,no,no,no
streamingmovies,no,no,no,no,no
contract,month-to-month,one_year,month-to-month,one_year,month-to-month
paperlessbilling,yes,no,yes,no,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,no,no,yes,no,yes

In [178]:
df.totalcharges = pd.to_numeric(df['totalcharges'], errors='coerce')

In [179]:
df.totalcharges = df.totalcharges.fillna(0)

In [180]:
df.churn = (df.churn == 'yes').astype(int)

# Setting up validation framework

In [181]:
from sklearn.model_selection import train_test_split

In [182]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [183]:
df_train, df_val = train_test_split(df, test_size=0.25, random_state=1)

In [184]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [185]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

In [186]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

# Exploratory Data Analysis

In [187]:
global_churn = round(df_full_train.churn.mean(),2)
global_churn

np.float64(0.27)

In [188]:
numericals = ['tenure', 'monthlycharges', 'totalcharges']

categoricals = ['gender', 'seniorcitizen', 'partner', 'dependents',
       'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod']

In [189]:
df_full_train[categoricals].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [190]:
from IPython.display import display

# Feature importance:

In [191]:
for c in categoricals:
  print(c)
  df_group = df_full_train.groupby(c).churn.agg(['mean', 'count'])
  df_group['diff'] = df_group['mean'] - global_churn
  df_group['risk'] = df_group['mean'] / global_churn

  display(df_group)
  print()
  print()

gender

            mean  count      diff      risk
gender
female  0.276824   2796  0.006824  1.025274
male    0.263214   2838 -0.006786  0.974865

seniorcitizen

                   mean  count      diff      risk
seniorcitizen
0              0.242270   4722 -0.027730  0.897297
1              0.413377    912  0.143377  1.531027

partner

             mean  count      diff      risk
partner
no       0.329809   2932  0.059809  1.221515
yes      0.205033   2702 -0.064967  0.759383

dependents

                mean  count      diff      risk
dependents
no          0.313760   3968  0.043760  1.162074
yes         0.165666   1666 -0.104334  0.613579

phoneservice

                  mean  count      diff      risk
phoneservice
no            0.241316    547 -0.028684  0.893764
yes           0.273049   5087  0.003049  1.011292

multiplelines

                      mean  count      diff      risk
multiplelines
no                0.257407   2700 -0.012593  0.953361
no_phone_service  0.241316    547 -0.028684  0.893764
yes               0.290742   2387  0.020742  1.076820

internetservice

                     mean  count      diff      risk
internetservice
dsl              0.192347   1934 -0.077653  0.712398
fiber_optic      0.425171   2479  0.155171  1.574709
no               0.077805   1221 -0.192195  0.288167

onlinesecurity

                         mean  count      diff      risk
onlinesecurity
no                   0.420921   2801  0.150921  1.558967
no_internet_service  0.077805   1221 -0.192195  0.288167
yes                  0.153226   1612 -0.116774  0.567503

onlinebackup

                         mean  count      diff      risk
onlinebackup
no                   0.404323   2498  0.134323  1.497494
no_internet_service  0.077805   1221 -0.192195  0.288167
yes                  0.217232   1915 -0.052768  0.804564

deviceprotection

                         mean  count      diff      risk
deviceprotection
no                   0.395875   2473  0.125875  1.466205
no_internet_service  0.077805   1221 -0.192195  0.288167
yes                  0.230412   1940 -0.039588  0.853379

techsupport

                         mean  count      diff      risk
techsupport
no                   0.418914   2781  0.148914  1.551534
no_internet_service  0.077805   1221 -0.192195  0.288167
yes                  0.159926   1632 -0.110074  0.592320

streamingtv

                         mean  count      diff      risk
streamingtv
no                   0.342832   2246  0.072832  1.269747
no_internet_service  0.077805   1221 -0.192195  0.288167
yes                  0.302723   2167  0.032723  1.121195

streamingmovies

                         mean  count      diff      risk
streamingmovies
no                   0.338906   2213  0.068906  1.255209
no_internet_service  0.077805   1221 -0.192195  0.288167
yes                  0.307273   2200  0.037273  1.138047

contract

                    mean  count      diff      risk
contract
month-to-month  0.431701   3104  0.161701  1.598893
one_year        0.120573   1186 -0.149427  0.446568
two_year        0.028274   1344 -0.241726  0.104718

paperlessbilling

                      mean  count      diff      risk
paperlessbilling
no                0.172071   2313 -0.097929  0.637300
yes               0.338151   3321  0.068151  1.252412

paymentmethod

                               mean  count      diff      risk
paymentmethod
bank_transfer_(automatic)  0.168171   1219 -0.101829  0.622854
credit_card_(automatic)    0.164339   1217 -0.105661  0.608661
electronic_check           0.455890   1893  0.185890  1.688482
mailed_check               0.193870   1305 -0.076130  0.718036

# Feature importance: Mutual information
- Measure relative importance of categorical variables

In [192]:
from sklearn.metrics import mutual_info_score

In [193]:
mutual_info_score(df_full_train.churn, df_full_train.contract)

np.float64(0.0983203874041556)

In [194]:
def mutual_info_churn_score(series):
  return mutual_info_score(series, df_full_train.contract)

In [195]:
mi = df_full_train[categoricals].apply(mutual_info_churn_score).sort_values(ascending=False)
mi

contract            0.998336
techsupport         0.116602
onlinesecurity      0.093611
deviceprotection    0.092025
paymentmethod       0.074191
onlinebackup        0.069242
streamingmovies     0.056707
streamingtv         0.054909
partner             0.046238
internetservice     0.042968
dependents          0.029329
paperlessbilling    0.013620
seniorcitizen       0.010747
multiplelines       0.006042
gender              0.000074
phoneservice        0.000067
dtype: float64