In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'
!wget $data -O data-week-3.csv

--2026-05-19 13:22:29--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 977501 (955K) [text/plain]
Saving to: ‘data-week-3.csv’

data-week-3.csv     100%[===================>] 954.59K  1.73MB/s    in 0.5s

2026-05-19 13:22:37 (1.73 MB/s) - ‘data-week-3.csv’ saved [977501/977501]

In [3]:
df = pd.read_csv('data-week-3.csv')

# Data preparation

In [4]:
df.columns = df.columns.str.lower()

strings = list(df.dtypes[df.dtypes == 'str'].index)

for col in strings:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [5]:
#check dtypes to change to apprropriate data types 
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                   str
dtype: object

In [6]:
df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce')

In [7]:
df.totalcharges.dtypes

dtype('float64')

In [8]:
df.totalcharges = df.totalcharges.fillna(0)

In [9]:
df.churn = (df.churn == 'yes').astype(int)

df.churn.head()

0    0
1    0
2    1
3    0
4    1
Name: churn, dtype: int64

# Setting up the validation framework
- train/validation/test

In [50]:
df = df[[
 'gender',
 'seniorcitizen',
 'partner',
 'dependents',
 'tenure',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod',
 'monthlycharges',
 'totalcharges',
 'churn']]

In [51]:
from sklearn.model_selection import  train_test_split

In [52]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
len(df_full_train), len(df_test)

(5634, 1409)

In [53]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [54]:
df_train = df_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)

In [55]:
y_train = df_train.churn.values
y_test = df_test.churn.values
y_val = df_val.churn.values

del df_train['churn']
del df_test['churn']
del df_val['churn']

# EDA

In [56]:
df_full_train = df_full_train.reset_index(drop=True)

### check for missing values

In [57]:
df_full_train.isnull().sum()

gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [58]:
#calculating the churn rate

global_churn_rate = round(df_full_train.churn.mean(), 2)
global_churn_rate

np.float64(0.27)

In [59]:
numerical_variables = ['tenure', 'monthlycharges', 'totalcharges']

categorical_variables = [ 'gender', 'seniorcitizen', 'partner', 'dependents',
       'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod']

In [60]:

df.columns = df.columns.str.lower().str.replace(' ', '_')
strings = list(df.dtypes[df.dtypes == 'str'].index)
for col in strings:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [61]:
df_full_train[categorical_variables]

,gender,seniorcitizen,partner,dependents,phoneservice,multiplelines,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod
0,male,0,yes,yes,yes,no,no,no_internet_service,no_internet_service,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check
1,female,0,no,no,yes,no,dsl,yes,yes,yes,yes,no,yes,one_year,no,credit_card_(automatic)
2,male,0,yes,no,yes,yes,dsl,yes,yes,no,yes,no,no,two_year,no,bank_transfer_(automatic)
3,male,0,yes,yes,yes,yes,dsl,yes,no,yes,yes,yes,yes,one_year,no,electronic_check
4,male,0,no,no,yes,no,dsl,yes,yes,no,yes,yes,no,one_year,no,electronic_check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5629,male,1,no,no,yes,yes,fiber_optic,no,no,yes,no,yes,yes,month-to-month,yes,electronic_check
5630,male,0,no,yes,yes,no,no,no_internet_service,no_internet_service,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check
5631,male,0,no,no,yes,yes,fiber_optic,no,yes,yes,no,yes,yes,month-to-month,yes,electronic_check
5632,male,0,no,no,yes,yes,dsl,no,yes,no,no,no,no,month-to-month,yes,mailed_check
5633,female,0,yes,yes,yes,no,dsl,yes,yes,no,yes,no,yes,two_year,no,bank_transfer_(automatic)

# Feature importance
- Evaluate churn rate within different groups

In [62]:
round(df_full_train.groupby('gender').churn.mean(), 2)

gender
female    0.28
male      0.26
Name: churn, dtype: float64

In [63]:
round(df_full_train.groupby('partner').churn.mean(), 2)

partner
no     0.33
yes    0.21
Name: churn, dtype: float64

In [64]:
from IPython.display import display

In [65]:
for col in categorical_variables:
    print(col)
    df_group =  df_full_train.groupby(col).churn.agg(['mean', 'count'])
    df_group['diff'] = df_group['mean'] - global_churn_rate
    df_group['risk_rate'] = df_group['mean'] / global_churn_rate
    display(df_group)
    print()

gender

            mean  count      diff  risk_rate
gender
female  0.276824   2796  0.006824   1.025274
male    0.263214   2838 -0.006786   0.974865

seniorcitizen

                   mean  count      diff  risk_rate
seniorcitizen
0              0.242270   4722 -0.027730   0.897297
1              0.413377    912  0.143377   1.531027

partner

             mean  count      diff  risk_rate
partner
no       0.329809   2932  0.059809   1.221515
yes      0.205033   2702 -0.064967   0.759383

dependents

                mean  count      diff  risk_rate
dependents
no          0.313760   3968  0.043760   1.162074
yes         0.165666   1666 -0.104334   0.613579

phoneservice

                  mean  count      diff  risk_rate
phoneservice
no            0.241316    547 -0.028684   0.893764
yes           0.273049   5087  0.003049   1.011292

multiplelines

                      mean  count      diff  risk_rate
multiplelines
no                0.257407   2700 -0.012593   0.953361
no_phone_service  0.241316    547 -0.028684   0.893764
yes               0.290742   2387  0.020742   1.076820

internetservice

                     mean  count      diff  risk_rate
internetservice
dsl              0.192347   1934 -0.077653   0.712398
fiber_optic      0.425171   2479  0.155171   1.574709
no               0.077805   1221 -0.192195   0.288167

onlinesecurity

                         mean  count      diff  risk_rate
onlinesecurity
no                   0.420921   2801  0.150921   1.558967
no_internet_service  0.077805   1221 -0.192195   0.288167
yes                  0.153226   1612 -0.116774   0.567503

onlinebackup

                         mean  count      diff  risk_rate
onlinebackup
no                   0.404323   2498  0.134323   1.497494
no_internet_service  0.077805   1221 -0.192195   0.288167
yes                  0.217232   1915 -0.052768   0.804564

deviceprotection

                         mean  count      diff  risk_rate
deviceprotection
no                   0.395875   2473  0.125875   1.466205
no_internet_service  0.077805   1221 -0.192195   0.288167
yes                  0.230412   1940 -0.039588   0.853379

techsupport

                         mean  count      diff  risk_rate
techsupport
no                   0.418914   2781  0.148914   1.551534
no_internet_service  0.077805   1221 -0.192195   0.288167
yes                  0.159926   1632 -0.110074   0.592320

streamingtv

                         mean  count      diff  risk_rate
streamingtv
no                   0.342832   2246  0.072832   1.269747
no_internet_service  0.077805   1221 -0.192195   0.288167
yes                  0.302723   2167  0.032723   1.121195

streamingmovies

                         mean  count      diff  risk_rate
streamingmovies
no                   0.338906   2213  0.068906   1.255209
no_internet_service  0.077805   1221 -0.192195   0.288167
yes                  0.307273   2200  0.037273   1.138047

contract

                    mean  count      diff  risk_rate
contract
month-to-month  0.431701   3104  0.161701   1.598893
one_year        0.120573   1186 -0.149427   0.446568
two_year        0.028274   1344 -0.241726   0.104718

paperlessbilling

                      mean  count      diff  risk_rate
paperlessbilling
no                0.172071   2313 -0.097929   0.637300
yes               0.338151   3321  0.068151   1.252412

paymentmethod

                               mean  count      diff  risk_rate
paymentmethod
bank_transfer_(automatic)  0.168171   1219 -0.101829   0.622854
credit_card_(automatic)    0.164339   1217 -0.105661   0.608661
electronic_check           0.455890   1893  0.185890   1.688482
mailed_check               0.193870   1305 -0.076130   0.718036

### Feature importance: mutual information

In [66]:
from sklearn.metrics import mutual_info_score

In [67]:
def mutual_info_churn_score(series):
    return mutual_info_score(series, df_full_train.churn)

In [68]:
mi = df_full_train[categorical_variables].apply(mutual_info_churn_score)
mi.sort_values(ascending=False)

contract            0.098320
onlinesecurity      0.063085
techsupport         0.061032
internetservice     0.055868
onlinebackup        0.046923
deviceprotection    0.043453
paymentmethod       0.043210
streamingtv         0.031853
streamingmovies     0.031581
paperlessbilling    0.017589
dependents          0.012346
partner             0.009968
seniorcitizen       0.009410
multiplelines       0.000857
phoneservice        0.000229
gender              0.000117
dtype: float64

### Feature importance: correlation
- correlation coefficient

In [69]:
df_full_train[numerical_variables].corrwith(df_full_train.churn).abs()

tenure            0.351885
monthlycharges    0.196805
totalcharges      0.196353
dtype: float64

# One-hot encoding
- use scikit learn

In [70]:
from sklearn.feature_extraction import DictVectorizer

In [71]:
dv = DictVectorizer(sparse=False)

In [72]:
train_dict = df_train.to_dict(orient='records') #convert the data frame into a dictionary
test_dict = df_test.to_dict(orient='records')
val_dict = df_val.to_dict(orient='records')

In [73]:
dv.fit(train_dict) #fit the data before transforming
X_train = dv.transform(train_dict)
X_test = dv.transform(test_dict)
X_val = dv.transform(val_dict)

# Logistic regression
- Train a model with scikit-learn
- Apply it to the validation dataset
- Calculate the accuracy
- Train a model with Scikit-Learn
- Apply it to the validation dataset
- Calculate the accuracy

In [74]:
from sklearn.linear_model import LogisticRegression

In [75]:
model = LogisticRegression(solver='lbfgs')
model.fit(X_train, y_train)

/home/waltermokwena/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [76]:
#model w0
model.intercept_[0]

np.float64(-0.1109287445794238)

In [77]:
#model weights
model.coef_[0].round(3)

array([ 0.564, -0.154, -0.519, -0.013, -0.095,  0.071, -0.098, -0.082,
       -0.033, -0.076, -0.354,  0.343, -0.098,  0.002, -0.251,  0.162,
       -0.02 ,  0.066, -0.098, -0.076,  0.251, -0.098, -0.261, -0.228,
        0.119, -0.121,  0.012, -0.095, -0.03 ,  0.045, -0.028,  0.162,
       -0.271,  0.221, -0.097, -0.098,  0.087, -0.05 , -0.098,  0.039,
        0.194, -0.098, -0.205, -0.072,  0.   ])

In [78]:
#using the model to predict the probability of churning 
y_pred = model.predict_proba(X_val)[:, 1]

In [79]:
churn_decision = (y_pred >= 0.5)

In [80]:
#check model accuracy
(y_val == churn_decision).mean()

np.float64(0.801277501774308)

In [81]:
# creating a data frame to check compare the model results with actual results
df_pred = pd.DataFrame()
df_pred['probability'] = y_pred
df_pred['prediction'] = churn_decision.astype(int)
df_pred['actual'] = y_val

In [82]:
df_pred

      probability  prediction  actual
0        0.007863           0       0
1        0.209928           0       0
2        0.223710           0       0
3        0.561123           1       1
4        0.219586           0       0
...           ...         ...     ...
1404     0.297790           0       0
1405     0.035463           0       1
1406     0.150149           0       0
1407     0.776681           1       1
1408     0.810358           1       1

[1409 rows x 3 columns]

# Model interpretation

In [83]:
dict(zip(dv.get_feature_names_out(), model.coef_[0].round(3)))

{'contract=month-to-month': np.float64(0.564),
 'contract=one_year': np.float64(-0.154),
 'contract=two_year': np.float64(-0.519),
 'dependents=no': np.float64(-0.013),
 'dependents=yes': np.float64(-0.095),
 'deviceprotection=no': np.float64(0.071),
 'deviceprotection=no_internet_service': np.float64(-0.098),
 'deviceprotection=yes': np.float64(-0.082),
 'gender=female': np.float64(-0.033),
 'gender=male': np.float64(-0.076),
 'internetservice=dsl': np.float64(-0.354),
 'internetservice=fiber_optic': np.float64(0.343),
 'internetservice=no': np.float64(-0.098),
 'monthlycharges': np.float64(0.002),
 'multiplelines=no': np.float64(-0.251),
 'multiplelines=no_phone_service': np.float64(0.162),
 'multiplelines=yes': np.float64(-0.02),
 'onlinebackup=no': np.float64(0.066),
 'onlinebackup=no_internet_service': np.float64(-0.098),
 'onlinebackup=yes': np.float64(-0.076),
 'onlinesecurity=no': np.float64(0.251),
 'onlinesecurity=no_internet_service': np.float64(-0.098),
 'onlinesecurity=yes': np.float64(-0.261),
 'paperlessbilling=no': np.float64(-0.228),
 'paperlessbilling=yes': np.float64(0.119),
 'partner=no': np.float64(-0.121),
 'partner=yes': np.float64(0.012),
 'paymentmethod=bank_transfer_(automatic)': np.float64(-0.095),
 'paymentmethod=credit_card_(automatic)': np.float64(-0.03),
 'paymentmethod=electronic_check': np.float64(0.045),
 'paymentmethod=mailed_check': np.float64(-0.028),
 'phoneservice=no': np.float64(0.162),
 'phoneservice=yes': np.float64(-0.271),
 'seniorcitizen': np.float64(0.221),
 'streamingmovies=no': np.float64(-0.097),
 'streamingmovies=no_internet_service': np.float64(-0.098),
 'streamingmovies=yes': np.float64(0.087),
 'streamingtv=no': np.float64(-0.05),
 'streamingtv=no_internet_service': np.float64(-0.098),
 'streamingtv=yes': np.float64(0.039),
 'techsupport=no': np.float64(0.194),
 'techsupport=no_internet_service': np.float64(-0.098),
 'techsupport=yes': np.float64(-0.205),
 'tenure': np.float64(-0.072),
 'totalcharges': np.float64(0.0)}